apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - name: my-web
        image: chunsumin/my-web-app:f62988932372eee58d3032c7d506f9d2676563bb
        ports:
        - containerPort: 80
