apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - name: my-web
        image: chunsumin/my-web-app:bdaa12831b619ea21c56ab1c42de3bda00919fd3
        ports:
        - containerPort: 80
