apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-chatbot
  template:
    metadata:
      labels:
        app: my-chatbot
    spec:
      imagePullSecrets:       # ğŸ‘ˆ [ì¶”ê°€] Harbor ì—´ì‡  ì‚¬ìš© ì„ ì–¸
      - name: regcred
      containers:
      - name: my-web
        # ğŸ‘‡ [ìˆ˜ì •] ì£¼ì†Œ ì•ì— Harbor IP ë¶™ì´ê¸°
        image: 192.168.10.20/library/my-web-app:44bcbab5fd6cf8a6a6daf314e37358cf16f2f36b
        ports:
        - containerPort: 80
